services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    volumes:
      - ./frontend:/var/www/html/frontend
      - ./backend:/var/www/html/backend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/var/www/html/frontend
      - ./backend:/var/www/html/backend
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
